# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'ZIMKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZIMKitDemo
  pod 'ZIMKit','>= 2.5.1'
  pod 'ZegoUIKitPrebuiltCall','>= 2.12.1'
  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings["CODE_SIGN_IDENTITY"] = ''
           end
      end
    end
  end

end
